services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: